FROM base

# -- Layer: JupyterLab

ARG spark_version=3.0.0
ARG jupyterlab_version=2.1.5

RUN apt-get update -y && \
    apt-get install -y python3-pip

RUN pip3 install pyspark==${spark_version} jupyterlab==${jupyterlab_version}

# add extra libraries
RUN pip3 install wget pandas==1.1.2 

# -- Runtime

EXPOSE 8888
WORKDIR /opt/notebooks
CMD jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token=
